### ISSUE TITLE
Wire.h issue ...

### ISSUE THREAD

**Issue by RandoSY** [kriswiner/Dragonfly#9]
Howdy,

Catching this error: 

In file included from C:\Users\randa\Desktop\Dragonfly STM32L47696 Development Board\Dragonfly-master\MPU9250Basic\MPU9250Basic.ino:16:0:

C:\Users\randa\AppData\Local\Arduino15\packages\grumpyoldpizza\hardware\stm32l4\0.0.28\libraries\Wire\src/Wire.h:122:10: note: void TwoWireEx::begin(TwoWireExPins)

     void begin(TwoWireExPins pins = TWI_PINS_20_21);

I was thinking that I do have the correct core installed,  and selected.  Not sure why I am pulling incorrect wire.h ?

Thoughts? Thanks!!!

**Comment by kriswiner** [comment]
No idea, shouldn't this be Wire.begin();?

Are you using a Dragonfly, selecting Dragonfly board variant?

**Comment by RandoSY** [comment]
Hello, thanks so much for the consideration of your prompt reply. :)

I switched over to an Arduino instance on a Linux VM, (1.8.9), with a much less "messy" install, and of course made sure I was pulling the board definitions from here ...

https://grumpyoldpizza.github.io/arduino-STM32L4/package_STM32L4_boards_index.json

And caught the same error, so perhaps it's just an upgrade from 1.6.x to 1.8.x and the way they have their wire.h setup?

I'm just evaluating the one program, I will experiment with the others ...

Best,

R.

**Comment by kriswiner** [comment]
The core you pulled from does not use the Arduino.cc Wire.h, the core has
its own Wire.h so if you are selecting random functions from the L4 core
repository I am not sure how this could possibly work at all...

If you use the L4 Arduino core you will need to have installed also the
SAMD boards in the Arduino IDE since we use some of these functions for the
compiler.

**Comment by RandoSY** [comment]
Yes, that's exactly it, the example program I'm running is preferentially pulling I2C support from some other library.  On my Ubuntu instance which is a much cleaner install, all new this week, I was able to get the aforementioned demo code to compile by changing the invocation of wire.begin to just

1.) wire.begin();

2.) Installing the **Adafruit SAMD support**, Arduino SAMD support was not sufficient.

Thanks!
